apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_USERNAME: YWRtaW4=              # admin
  DB_PASSWORD: QWRtaW4hMTIz          # Admin!123
  REDIS_PASSWORD: cmVkaXNAcDEyMw==   # redis@p123
  JWT_SECRET: c2VjcmV0LWtleQ==       # secret-key
  EMAIL_SMTP_PASSWORD: U21wQDEyMw==  # Smp@123
  THIRD_PARTY_API_KEY: QUJDREVGRw==  # ABCDEFG
